name: Build Windows EXE (PyInstaller)
on:
  workflow_dispatch:
  push:
    paths:
      - "scrapper.py"
      - "requirements.py"
      - ".github/workflows/build-windows-exe.yml"
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.py
          pip install pyinstaller
      
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name "WheelersScraper" scrapper.py
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: WheelersScraper-windows
          path: dist/WheelersScraper.exe
